export const REQUEST_QR = 'REQUEST_QR';
export const RECEIVE_UUID = 'RECEIVE_UUID';
export const POLL_RESULT = 'POLL_RESULT';
export const RECEIVE_QR_SUCCESS = 'RECEIVE_QR_SUCCESS';
export const RECEIVE_QR_FAILURE = 'RECEIVE_QR_FAILURE';
